language: python

python:
  - "3.5"
  - "3.6"
  - "pypy3"

env:
  - DJANGO_VERSION=1.10.8
  - DJANGO_VERSION=1.11.11
  - DJANGO_VERSION=2.0.3

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -q -e ".[dev]" --upgrade-strategy only-if-needed

script:
  - coverage run --source=. runtests.py

after_success:
  - codecov
