language: python

python:
  - "3.5"
  - "3.6"
  - "pypy3"

env:
  - DJANGO_VERSION=1.10.8
  - DJANGO_VERSION=1.11.7

install:
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install

script: ./runtests
